### ISSUE TITLE
Importing a CJS dependency through a local typescript dependency in a pnpm workspace fails

### ISSUE THREAD

**Issue by nitedani** [cyco130/vavite#11]
I'm not sure whether this is an issue with vite or vavite. I tried to isolate the issue as much as I could.
This is a possible vite regression, but I need your help to report it as such

Reproduction:
clone https://github.com/nitedani/vite-import-bug

Error: exports is not defined

How to get the error:
1. cd apps/app
2. pnpm i
3. pnpm start:vavite

How to make it work:
1. replace vite3 -> vite2 in package.json
2. cd apps/app
3. pnpm i
4. pnpm start:vavite

OR

1. cd apps/app
2. pnpm i --shamefully-hoist
3. pnpm start:vavite

**Comment by cyco130** [comment]
> This is a possible vite regression, but I need your help to report it as such

Seems like it on first inspection. I will take a better look tomorrow. Thanks for reporting!

**Comment by cyco130** [comment]
First of all, I'm not sure it's legal to import a `.ts` file from `node_modules`. I would think it isn't: Transforming files outside of the root should be out of scope, and if it did work before it must have been an accident.

But it keeps failing even when I change the file name to `.mjs`, I had to manually add `package` to `ssr.external` to force Vite to treat it as external and then everything works.

In any case it's all happening in Vite and not vavite, you can confirm by creating a Vite server in middleware mode and loading the module with `ssrLoadModule`, removing vavite from the equation.

**Comment by nitedani** [comment]
Thank you for finding the cause!
I read about the .ts imports here: https://turborepo.com/posts/you-might-not-need-typescript-project-references
You can close this if you want to
