### ISSUE TITLE
Vike / Breakpoint position wrong

### ISSUE THREAD

**Issue by aheissenberger** [cyco130/vavite#118]
`vavite serve` in the `vscode Javascript Debug Terminal` will break to a different position im Code somewhere after the set breakpoint.

Setup:
* vavite: 4.1.2
* vite: 5.4.1
* vike: 0.4.188
* Hono: 4.5.6

**vite.config.ts:**
```ts
import { vavite } from "vavite";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";
import vike from "vike/plugin";

export default defineConfig({
  plugins: [
    vike({disableAutoFullBuild: true}),
    react({}),
    vavite({
      handlerEntry: "/hono-entry.vavite.ts",
      serveClientAssetsInDev: true,
      standalone: false,
    }),
  ],
});
```

**Comment by cyco130** [comment]
Unfortunately this is a long standing issue with Vite's SSR dev server. The best fix I have use to be the `@vavite/node-loader` package but [it only works on Node 18](https://github.com/cyco130/vavite/issues/39).

You might want to try adding the experimental `useViteRuntime: true` option to your `vavite` config. It's supposed to solve this problem but I'm not 100% sure.

Hopefully the upcoming [Vite Environment API](https://github.com/vitejs/vite/discussions/16358) will finally fix this.
