### ISSUE TITLE
Any help with HMR issues?

### ISSUE THREAD

**Issue by bensaufley** [cyco130/vavite#119]
I apologize for the vague title; it reflects that I'm not sure where to start debugging this.

This is such a useful library so thank you! I've got a project I'm working on that uses Fastify and Preact, but HMR isn't working properly. The full repo is here: https://github.com/bensaufley/audiobook-catalog – the latest code is ~~on [the `bs-tags` branch](https://github.com/bensaufley/audiobook-catalog/tree/bs-tags)~~ in `main`. It's all run in docker and if you wanted to run it it _should_ be as simple as running `script/server`.

But the important stuff, I think:

`vite.config.ts`:
```ts
/// <reference types="vite/client" />
/* eslint-disable import/no-extraneous-dependencies */
import preact from '@preact/preset-vite';
import { resolve } from 'node:path';
import { vavite } from 'vavite';
import { defineConfig, type UserConfig } from 'vite';
import { createHtmlPlugin } from 'vite-plugin-html';
import svgr from 'vite-plugin-svgr';

const dirname = typeof __dirname === 'undefined' ? import.meta.dirname : __dirname;

const viteResolve: UserConfig['resolve'] = {
  alias: [
    { find: /^~client(?=\/)/, replacement: resolve(dirname, 'src/client') },
    // etc
  ],
  extensions: ['.mjs', '.js', '.ts', '.jsx', '.tsx', '.json'],
};

// https://vitejs.dev/config/
export default defineConfig({
  buildSteps: [
    {
      name: 'client',
      config: {
        build: {
          manifest: true,
          outDir: '.build/client',
        },
        resolve: viteResolve,
        root: '.',
        plugins: [],
      },
    },
    {
      name: 'server',
      config: {
        define: {
          'process.env.DB_NAME': JSON.stringify(process.env.DB_NAME || 'books'),
        },
        build: {
          outDir: '.build/server',
          ssr: 'src/server',
          target: 'node22',
        },
      },
    },
  ],
  resolve: viteResolve,
  server: {
    host: '0.0.0.0',
    port: 3000,
    strictPort: true,
    hmr: {
      port: 6453,
    },
  },
  plugins: [
    preact(),
    svgr({
      svgrOptions: {
        svgProps: {
          role: 'img',
        },
      },
    }),
    vavite({
      bundleSirv: false,
      serverEntry: 'src/server/index.ts',
      reloadOn: 'any-change',
      serveClientAssetsInDev: true,
    }),
    createHtmlPlugin({
      entry: resolve(dirname, 'src/client/index.tsx'),
      template: 'src/client/index.html',
    }),
  ],
});
```

Setting up the server:

```ts

  let devServerOpts: Pick<FastifyServerOptions<Server, FastifyBaseLogger>, 'serverFactory'> | undefined;
  if (import.meta.env.DEV) {
    // eslint-disable-next-line import/no-extraneous-dependencies
    const { default: devServer } = await import('vavite/http-dev-server');
    devServerOpts = {
      serverFactory: (handler) => {
        devServer!.on('request', handler);
        return devServer!;
      },
    };
  }

  const server = Fastify({
    logger: {
      level: sanitizeLogLevel(process.env.LOG_LEVEL),
      ...(import.meta.env.DEV
        ? {
            transport: {
              target: 'pino-pretty',
            },
          }
        : {}),
    },
    ...devServerOpts,
  });

  // ...

  const viteDevServer = import.meta.env.DEV ? (await import('vavite/vite-dev-server')).default : undefined;
  server.get('/*', async (req, res) => {
    if (import.meta.env.DEV) {
      const index = await readFile(resolve(import.meta.dirname, '../client/index.html'), 'utf-8');
      res.header('Content-Type', 'text/html');
      return res.send(await viteDevServer!.transformIndexHtml(req.url, index));
    }

    return res.sendFile('index.html', resolve(import.meta.dirname, '../client/'));
  });
```

Starting the server:

```ts
  let devServer: typeof httpDevServer | undefined;
  if (import.meta.env.DEV) {
    // eslint-disable-next-line import/no-extraneous-dependencies
    ({ default: devServer } = await import('vavite/http-dev-server'));
  }
  await server.listen({
    port: (devServer?.address() as AddressInfo | undefined | null)?.port ?? 3000,
    host: '0.0.0.0',
  });
```

The result is:

- Server: when I make a change:
   - I see `@vavite/reloader: Loading server entry` in my server
   - The changes I've made don't take effect
   - I have to restart my server manually
- Client
    - I do see `[vite] connecting...` and `[vite] connected`
    - when I make a change:
       - Nothing happens
       - When I switch to `static-deps-change` rather than `any-change` I get 
[`cannot read properties of undefined (reading 'has')`](https://github.com/user-attachments/assets/98ec80df-68fd-4edb-9d4c-670f86f813de) from `@vavite/reloader/dist/index.js:208:63`
       - Reloading the page shows the changes (no need to restart the server)

I'll be honest getting all this working took a lot of fiddling and I know the "recommended" method is setting my app as middleware rather than passing vavite into my server, so I'm not sure if there's an easy way to get help on this but I'd love to get this working properly.

The positives:
- It runs locally, just HMR is buggy or ineffective
- It builds, and runs in "production"
So the major goal of "use one build system for server and client" is achieved here and I love that. I just would love to get HMR working. I think it did, at one point during dev, but I have no idea when that was and I might just be mistaken.

**Comment by cyco130** [comment]
Hi,

I can't find the branch you're referring to. And the main branch gives me a seemingly unrelated error:

```
ENOENT: no such file or directory, mkdir '/db'
```

So I can't reproduce at the moment. But I have a few observations:

## `import.meta.hot`

Vite doesn't support hot reloading on its SSR module graph. So `import.meta.hot` etc. have no effect outside of client-side files. The upcoming [Vite Environment API](https://github.com/vitejs/vite/discussions/16358) will hopefully solve this.

But it can reload affected modules on the next request so the end result is similar to HMR.

## `vavite/vite-dev-server`

The following gymnastics are unnecessary:

```ts
const viteDevServer = import.meta.env.DEV ? (await import('vavite/vite-dev-server')).default : undefined;
```

`vavite` already does this for you. Just do `import viteDevServer from "vavite/vite-dev-server"` and it will be `undefined` in production and won't pull in any of Vite.

## `vavite/http-dev-server`

I strongly recommend you to switch to `handlerEntry` instead. `vavite/http-dev-server` is a hack and I regret publishing it. If you absolutely need to control the creation of the server, you can still give a `serverEntry` and it will be used for production. You simply can't control the server creation in dev anyway since `vavite` uses Vite's dev server which is created by Vite.

**Comment by bensaufley** [comment]
Ah shoot, sorry, `bs-tags` got merged. Latest is in `main`. What command are you running where you're encountering that `/db` error? Was it `script/server`? That's a strange error I'm not even sure how to parse: "no such directory" when _making_ the directory?

- `import.meta.hot`: honestly, this was a late edition. Just trying stuff to see if it would do anything. But that's good to know. I'll def remove that.
- `import.meta.env.DEV?`: but it will still need to be _installed_ on the prod image, right? Even if what it returns is `undefined`, Node will throw an error if I try to `import` it and it's not installed? It's not a huge deal but I don't like the idea of needing a dev dependency installed in Prod, even if it's not in use.
- I'll look into `handlerEntry` some more. TBH I think I _did_ try it at one point and couldn't get it to work in a way I was satisfied with, but I don't remember exactly what the issue was. I do think one of the reasons I didn't want to do that was, again, dev assets in prod: I don't like building my prod code around dev requirements; the addition of `sirv` seemed unnecessary and undesirable.

**Comment by cyco130** [comment]
> import.meta.env.DEV?: but it will still need to be installed on the prod image, right? Even if what it returns is undefined, Node will throw an error if I try to import it and it's not installed? It's not a huge deal but I don't like the idea of needing a dev dependency installed in Prod, even if it's not in use.

No, it's a virtual module, it will be bundled with your code when you build it and the production code won't have any references to the package. And Vite is smart enough to optimize out any `if (viteDevServer) { ... }` checks in the code.

> I'll look into handlerEntry some more.

Have a look at the [Fastify example](https://github.com/cyco130/vavite/tree/main/examples/fastify). Skip the `lazy` part if you don't need it (it's a small optimization to load the routes lazily). And if you do need control when starting the server in prod, export `fastify` from `handler.ts` and use it like this in a `prod.ts` file:

```ts
import { fastify } from "./handler";

// This file will only run on production, it has no effect in dev mode.
// Do whatever else you need to do here before the server starts.

const port = Number(process.env.PORT) || 3000;
const host = process.env.HOST || "localhost";

fastify.listen(
  {
    port,
    host,
  },
  () => {
    console.log(`Server listening on http://${host}:${port}`);
  }
);
```

and add it to your `vite.config.ts`:

```ts
import { defineConfig } from "vite";
import { vavite } from "vavite";

export default defineConfig({
  plugins: [
    vavite({
      handlerEntry: "/handler.ts",
      serverEntry: "/prod.ts",
    }),
  ],
});
```

Have a look at the generated code in `dist/index.js` after `npm run build`. There will be no traces left from the dev-related stuff (including the `fastify.server.emit(...)` stuff required to make Fastify play nicely with `vavite`).

If it's still a no go, I'll have another look at your code when I have more time to see why it doesn't work for me.

**Comment by bensaufley** [comment]
Using both `handlerEntry` and `serverEntry` seems like a solution that's working great for me. Thanks!
