### ISSUE TITLE
dev server cannot be closed

### ISSUE THREAD

**Issue by qeleb** [cyco130/vavite#18]
I am using a React SSR Fastify server with Vavite. When I close the dev server (for example, using Ctrl+C on macOS), the terminal window fails to close. When you try to close it with Ctrl+C, the dev server ceases to work, but continues to show text & does not return control to the user.

This is actually evident even in the Fastify Stackblitz example using the current version of Vite & Vavite.

Can you take a look at this?

**Comment by cyco130** [comment]
Thanks for reporting. Maybe it's a macOS issue. I'll check on a mac and try to see what's going on.

**Comment by qeleb** [comment]
it’s worth noting that it appears to work perfectly— the terminal closes with no issues— when I use Express instead of Fastify.

**Comment by ohmree** [comment]
Getting this with nestjs + fastify as well, created a project using `@nestjs/cli` then manually added vavite to it as shown in the nestjs example.

With the stock express-based setup everything worked as expected but when I tried using the fastify adapter I ran into the same issue - trying to terminate the dev server makes the process freeze and spikes its cpu usage.

Here's my `main.ts`, pretty standard (cobbled together from the nestjs and fastify examples and the official nestjs docs):

```ts
/// <reference types="vite/client" />

import { NestFactory } from '@nestjs/core';
import httpDevServer from 'vavite/http-dev-server';
import { AppModule } from './app.module';
import { FastifyAdapter, NestFastifyApplication } from '@nestjs/platform-fastify';
import type { FastifyServerFactory, RawServerDefault } from 'fastify';
import type { AddressInfo } from 'node:net';

bootstrap();

async function bootstrap() {
  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    new FastifyAdapter(
      import.meta.env.DEV
        ? {
            serverFactory: (handler => {
              // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
              httpDevServer!.on('request', handler);
              // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
              return httpDevServer!;
            }) as FastifyServerFactory<RawServerDefault>,
          }
        : undefined,
    ),
  );
  if (import.meta.env.PROD) {
    const port = process.env.PORT ?? 3000;
    app.listen(port);
  } else {
    try {
      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
      await app.listen((httpDevServer!.address() as AddressInfo).port);
    } catch (e) {
      console.error(e);
      process.exit(1);
    }
  }
}
```

**Comment by cyco130** [comment]
I updated all examples to use `handlerEntry` instead of `serverEntry`.

`serverEntry` is unfortunately a hack. It happens to work under some circumstances but not always. I have a better way in mind to implement the same functionality in a much cleaner way if/when [this PR](https://github.com/vitejs/vite/pull/11411) lands on Vite.

Until then I'm unable to solve this, unfortunately. I'll keep it open as a reminder though :)

**Comment by cyco130** [comment]
This has been solved for sometime, alla examples are now working.
