### ISSUE TITLE
[question] run a callback on hmr reload

### ISSUE THREAD

**Issue by mgcrea** [cyco130/vavite#21]
Not a bug but a question,

Is there an easy way to run a callback when the handler has been reloaded by `vavite`?

I need to clean some global `PerformanceObserver` state that stacks up on every reload.

**Comment by cyco130** [comment]
By default Vavite re-evaluates the handler module before calling the handler if it was modified. You can clean up the global state at the module's top level. Or, if you need to run some code on the previous instance of the module (the one that is now disposed), you can store a clean up function in the global scope like this and call it:

```ts
import express from 'express';

// Declare types
declare global {
  var cleanup: undefined | (() => void);
}

// Call if previously installed.
global.cleanup?.();

// Install the new one
global.cleanup = () => {
  console.log('Do some cleanup');
};

// Initialize the app as usual

const app = express();

app.get('/', (req, res) => {
  res.send('Hello world!!!');
});

export default app;
```

Here's a full example: https://stackblitz.com/edit/github-ttanxg?file=server.ts
