### ISSUE TITLE
nestjs-vite-plugin-ssr example broken (HttpAdapterHost is undefined)

### ISSUE THREAD

**Issue by joshball** [cyco130/vavite#29]
Reproduce by following instructions in [README](https://github.com/cyco130/vavite/blob/main/examples/nestjs-vite-plugin-ssr/readme.md): `pnpm install && pnpm dev` (or `pnpm build`)

On running, when `VpsModule::onModuleInit()` is called, `this.httpAdapterHost` is undefined.

I looked around and found this older [issue](https://github.com/cyco130/vavite/issues/5), but the `vite.config.ts` has `esbuild:false`.

The `onModuleInit()` happens during the call to `NestFactory.create(AppModule)`, and I see the code after it `resolveHandler(await app.getHttpAdapter().getInstance())` is supposed to work, not sure  what is happening exactly.

I checked out a few other bugs like [this](https://github.com/nestjs/nest/issues/8174) and [this](https://github.com/nestjs/nest/issues/8076) but they don't seem relevant.

If I return from the function (instead of throwing an error), then the bootstrap goes through and I can verify `await app.getHttpAdapter().getInstance()` returns a valid instance, but, alas, this is a bit too late it seems. 

I also found (from the initial issue by nitedani) an [ssr repo](https://github.com/nitedani/vps-react-nestjs/blob/main/server/vite-ssr/ssr.module.ts), and tried that code.
It works, but it is considerably more involved and uses webpack. I managed to take the VPS module from that code and replace the current one, changing the app.module.ts and having to add the two config files in the repo ./config/vite.[client|server].config.ts

Because the structure is different, I ended up copying the src directory over as well. All said, I can actually see the app.get('*') being called, which means the VPS module at least works (and therefore the httpAdapterHost is being passed it). But pulling apart the the configs and other changes has me uncertain which change fixed it. Maybe in that server config.

At any rate, I wish I could give you more.

**Comment by cyco130** [comment]
For a quick fix, replace `swc(/* options */)` with `{ ...swc(/* options */), enforce: "pre" }` in your Vite config.

There's one more (unrelated) bug when using the dev server: If you encounter the following message on the browser console, restart the server:

```
[vite-plugin-ssr@0.4.90][Info] New deployed frontend detected. The next page navigation will use Server Routing instead of Client Routing.
```

I'll update the example once I fixed the second issue.

**Comment by cyco130** [comment]
Updated the examples.

**Comment by MrFoxPro** [comment]
@cyco130 Why SWC is needed for NestJS?

**Comment by cyco130** [comment]
> @cyco130 Why SWC is needed for NestJS?

Vite normally uses ESBuild to transpile TypeScript but ESBuild [has no support for TS decorators](https://github.com/evanw/esbuild/issues/104) that NestJS relies on.
