### ISSUE TITLE
error on vite-ssr-plugin dev launch

### ISSUE THREAD

**Issue by uplight-dev** [cyco130/vavite#41]
Could not resolve entry module "serve/index.html".
error during build:
RollupError: Could not resolve entry module "serve/index.html".

**Comment by krbtyr** [comment]
Hey there,

I've tried the ssr-react-express and nestjs-vite-plugin-ssr examples and am still getting this same issue even after 1.8.0:
`npx degit cyco130/vavite/examples/ssr-react-express`
`npx degit cyco130/vavite/examples/nestjs-vite-plugin-ssr`

**Comment by lulzsun** [comment]
Can also confirm, still getting issue with the fastify example.

**Comment by cyco130** [comment]
Fixed in 1.8.1.

@lulzsun Fastify example seems to have a second an unrelated bug. I [opened another](https://github.com/cyco130/vavite/issues/45) issue for it.
