### ISSUE TITLE
debug ssr server

### ISSUE THREAD

**Issue by ttrBetter** [cyco130/vavite#6]
We have converted our react build setup to use vavite, and we like the speed ;) 
How do we debug backend (server) if we run the vite command we cannot set breakpoints in the server code.

**Comment by cyco130** [comment]
Unfortunately it's an [upstream issue](https://github.com/vitejs/vite/issues/3288) with Vite: Vite's SSR transform don't support sourcemaps. There was [an effort](https://github.com/vitejs/vite/issues/3288) to make it work but it's not clear whether it's going forward. The way forward is more or less clear but someone needs to do the hard work.

Inserting `debugger` statements does work in the meantime.

**Comment by kemptone** [comment]
First off, love this project, thank you. 
I am basing a project off of one of the examples:
https://github.com/cyco130/vavite/tree/main/examples/ssr-react-express
I am having perhaps a noob issue when I import something like "@reduxjs/toolkit". It works great local, but when I yarn build, and then yarn start I get an error like this.

`import { configureStore } from "@reduxjs/toolkit";
         ^^^^^^^^^^^^^^
SyntaxError: Named export 'configureStore' not found. The requested module '@reduxjs/toolkit' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@reduxjs/toolkit';
const { configureStore } = pkg;`

I've spent most of the day on it, trying different things. Wondering if there is an easy answer?

**Comment by cyco130** [comment]
@kemptone this is an unrelated issue that doesn't belong here. But it comes up quite often so I [opened an issue](https://github.com/cyco130/vavite/issues/16) with some background and possible ways to fix it. Hope it helps.

**Comment by cyco130** [comment]
Fixed in #17.
