### ISSUE TITLE
Types are not being detected in v2

### ISSUE THREAD

**Issue by SimeonC** [cyco130/vavite#63]
It looks like in v2 the `exports` field in the package.json is missing meaning that not all configurations for tsconfig.json are supported.

For example if you open up the react-express stackblitz, it compiles fine but `vavite` (and others admittedly) have red squiggly lines under them as the types cannot be found.

Changing `node_modules/vavite/package.json` to be the following worked for me locally; (took inspiration from the [package definition of vite](https://github.com/vitejs/vite/blob/main/packages/vite/package.json) but vavite needs to be different for some reason.

```
  "type": "module",
  "module": "./dist/index.js",
  "types": "./dist/index.d.ts",
  "files": [
    "dist",
    "*.d.ts",
    "node-loader.mjs",
    "suppress-loader-warnings.cjs"
  ],
  "exports": {
    ".": {
      "import": "./dist/index.js",
      "require": "./dist/index.cjs",
      "types": "./dist/index.d.ts"
    },
```

My tsconfig.json relevant settings are;

```
    "module": "ES2020",
    "target": "ESNext",
    "moduleResolution": "Bundler",
```

**Comment by SimeonC** [comment]
Sorry about this looks like it is working correctly. Turns out I just didn't have it included in my tsconfig.json so it silently failed to load for some unknown reason. Typescript configuration is hard 😂

**Comment by cyco130** [comment]
> Typescript configuration is hard 😂

Tell me about it 😅

I prefer the [`typesVersions` trick](https://github.com/cyco130/vavite/blob/3cf52a5bd25deadde0949a52be31af1ad04c36d8/packages/vavite/package.json#L29) which I find cleaner than manually specifying each type definition file.

Just double-checked in any case and [Are the Types Wrong](https://arethetypeswrong.github.io/?p=vavite%402.0.1) suggests that everything's fine:

- `vavite/vite-dev-server` and `vavite/http-dev-server` are not meant to be consumed from CommonJS (they're virtual modules meant to be consumed from a Vite app), so the failures for "node16 (from CJS)" are OK.
- `vavite/node-loader` and `vavite/suppress-loader-warnings` don't need types, so those failures are also OK.

`publint` just [improved its type resolution error detection](https://github.com/bluwy/publint/releases/tag/v0.2.0#features:~:text=Improve%20warnings%20when%20the%20exported%20%22types%22%20condition%20has%20an%20invalid%20format%20in%20ESM%20or%20CJS.%20This%20ensures%20your%20library%27s%20types%20will%20work%20in%20both%20environments%20when%20dual%20publishing.%20(%2346)), so hopefully we'll have more confidence in our types from now on.

**Comment by SimeonC** [comment]
Nice, I hadn't heard of publint before. I'll probably try use that on my projects too.

Thanks for taking the time to reply, that error caused by not including the config file had me frustrated for a day before opening this. Annoyingly enough VSCode will happily tell you TS is running on the file, but give cryptic errors until it's included properly.

**Comment by jensbodal** [comment]
> Sorry about this looks like it is working correctly. Turns out I just didn't have it included in my tsconfig.json so it silently failed to load for some unknown reason. Typescript configuration is hard 😂

What was not included in your `tsconfig.json`?

**Comment by SimeonC** [comment]
> > Sorry about this looks like it is working correctly. Turns out I just didn't have it included in my tsconfig.json so it silently failed to load for some unknown reason. Typescript configuration is hard 😂
> 
> 
> 
> What was not included in your `tsconfig.json`?

The vite.config.ts file, had included subfolders but not root level ts files

**Comment by jensbodal** [comment]
Ah thanks just arrived at the same conclusion :)
