### ISSUE TITLE
A way to pass data from server to client (`ssr-react-express`)

### ISSUE THREAD

**Issue by CGuiho** [cyco130/vavite#69]
I looked at your `ssr-react-express` example ([here](https://github.com/cyco130/vavite/tree/main/examples/ssr-react-express)) and you did not pass any data from server to client, even the pathname.

**How would it be done?**

For example if I somehow get some data (from db, etc) and I use it on my component from the `server-entry.tsx`,  I would have an hydration error (and eventually a client side exception) unless I access it from my `client-entry.tsx`.

Thanks for `vavite`, I love it ❤️.

**Comment by cyco130** [comment]
Hi!

The usual way to do it is to serialize the props at server and put it in a script tag and read it from there and deserialize it in the client.

Have a look [here](https://stackblitz.com/edit/github-qfbneb?file=server-entry.tsx,client-entry.tsx). It's a very simple example that uses JSON as the serialization format.

That said, there are many other things that needs to be taken care of in a real app so you may need to "graduate" to `vite-plugin-ssr` (works well with vavite) or Rakkas (uses vavite), for example.

**Comment by CGuiho** [comment]
Yes, I did use serialization and it solved my problem, I thought it was another way to achieve that. 

I do know `vite-plugin-ssr`, I used it for a while,  but I wanted something more low level, because I have my own routing strategy, middleware,  etc.
