### ISSUE TITLE
Future of Vavite, Vite 3 and vite-plugin-ssr

### ISSUE THREAD

**Issue by Ontopic** [cyco130/vavite#7]
First, thanks for your extensions to Vite, really makes it a golden choice!

This is not really an issue, more an attempt to get some insights into the updates surrounding Vite 3, Vavite and `vite-plugin-ssr`.

I'm personally facing an issue for the base / root folder for this new combination, but I can hopefully hack myself through that for now and post a separate issue/fix for it later on. It's more that I'm feeling uncertain whether or not I should focus on getting these 3 tools to work together in my setup at the latest version, or perhaps stick to a Vite 2 with just vite-plugin-ssr, and keep vavite out of it until things are more "mature"?

I understand the "risks" involved nonetheless of working with the latest tools, some insights on the "readiness" of this setup would be very helpful though! So I at least know I'm focussing my efforts in the right place ;)

**Comment by Ontopic** [comment]
And would a betting-man that likes to run canary versions maybe switch to `hattip` yet, for example

**Comment by Ontopic** [comment]
Exactly the kind of update I was hoping for! Thanks a lot.

**Comment by cyco130** [comment]
Open issues give me anxiety so I'm gonna close this one :D Feel free to contact me on [Discord > Cubes # HatTip](https://discord.com/invite/vTvXzBMySh).

Contributions and pull requests are always welcome!
