### ISSUE TITLE
Question: how should we handle websocket connections?

### ISSUE THREAD

**Issue by giacomorebonato** [cyco130/vavite#85]
I am trying the following code to handle websocket connections to a Fastify server.
Do you see any bad side effect?

```javascript
if (httpDevServer) {
	httpDevServer.on('request', (request, reply) => {
		server.server.emit('request', request, reply)
	})	

	httpDevServer.on('upgrade', (request, socket, head) => {
		if (request?.url === '/trpc') {
			server.server.emit('upgrade', request, socket, head)
		}
	})

	httpDevServer.on('close', async () => {
		await server.close()
	})
} else {
	server.listen({
		host: env.HOST,
		port: env.PORT,
	})
}
```

**Comment by cyco130** [comment]
Hi!

I believe you're using an outdated example. I'd advise against using `vavite/http-dev-server` now, it's a hack and I'd like to remove it soon.

Instead try using `handlerEntry`. You can get a hold of the server via `request.socket.server`. You should also take care of not clashing with Vite's own websocket and removing the old upgrade listener when the entry is reloaded.

Here's a [full example](https://stackblitz.com/edit/github-xyaxlj?file=handler.ts).
