### ISSUE TITLE
Suupport for v3.0.4?

### ISSUE THREAD

**Issue by stychu** [cyco130/vavite#9]
Seems like support for v3x.x was not released to npm. I want to try combination with vavite and vite-plugin-ssr but it still yields peer dependency of 2.9.8

Im trying to get all together
1. Vavite
2. Vite-plugin-ssr
3. Fastify
4. tRPC

Getting  EADDRINUSE whenever I change files related to server

**Comment by stychu** [comment]
Got it working. Damn I love it ! You should correlate work with the vite-plugin-ssr to make a perfect combo with vite 💯 

Question tho. In order to make prod build i had to do `    "build": "vavite && vite build --ssr",` Can I somehow make this setup better?


```
package.json

"scripts": {
    "dev": "vite --open",
    "build": "vavite && vite build --ssr",
    "prod": "cross-env NODE_ENV=production node dist/server"
  },
  ```

```
vite.config.ts

import react from '@vitejs/plugin-react';
import ssr from 'vite-plugin-ssr/plugin';
import vavite from 'vavite';

import { UserConfig } from 'vite';

const config: UserConfig = {
  // build: {
  //   ssr: true,
  //   rollupOptions: {
  //     output: {
  //       // We have to disable this for multiple entries
  //       inlineDynamicImports: false,
  //     },
  //   },
  // },
  plugins: [
    vavite({
      serverEntry: '/server/index.ts',
      serveClientAssetsInDev: true,
    }),
    react(),
    ssr({ disableAutoFullBuild: true }),
  ],
};

export default config;
```

**Comment by cyco130** [comment]
Hi!

There's already a [`vite-plugin-ssr` example](https://github.com/cyco130/vavite/tree/main/examples/vite-plugin-ssr) that you can clone with `degit` or other tools, just check the example readme. It's a couple of patch releases behind on vite and vps but I just checked and it works with the latest versions too.



> Question tho. In order to make prod build i had to do ` "build": "vavite && vite build --ssr",` Can I somehow make this setup better?

Sure, check the [config](https://github.com/cyco130/vavite/blob/main/examples/vite-plugin-ssr/vite.config.ts) in the example. `vavite` extends Vite's config with a `buildSteps` property so a single `vavite` command is enough to build both the client and the server. Actually the latest vps also has that feature but it clashes with vavite's, hence the `disableAutoFullBuild: true` setting.

**Comment by stychu** [comment]
Ahhh yeah it's working.
I missed `/// <reference types="vavite/vite-config" />` at first and thats why I though it is not working.
Thank you!
