### ISSUE TITLE
CORS preflights with credentials drop because of vite dev server

### ISSUE THREAD

**Issue by macieklad** [cyco130/vavite#98]
I had integrated vavite with one of my local projects, and when sending a request with credentials to the app, the preflight gets rejected, as you cannot set `Acces-Control-Allow-Origin` to `*` with credentials. This is because preflights hit the vite dev server first and not the app server, therefore I'm wondering if we should add the 

```js
server : {
	cors: {
	  preflightContinue: true,
	}
}
```

option to the vite server by default, to handle CORS on the app level. This may affect asset handling though, so maybe the way is to add it and then add a middleware to the app in dev for just the vite assets with the correct CORS settings? I'm not sure, but it should be we could at least reflect it in the docs right now.

Will be happy to help if you think this may be needed 😄

**Comment by cyco130** [comment]
HI!

I understand the problem but I don't feel comfortable introducing a surprise factor by changing Vite's default CORS configuration in a plugin.

All examples in the repo are monoliths where the frontend is also served by the app, removing the need for any CORS setup. And if you do need separate frontend and backend servers, you can set up a proxy in your frontend server. E.g. something like this in Vite:

```ts
import type { UserConfigExport } from "vite";
import react from "@vitejs/plugin-react";

export default {
	plugins: [react()],
	server: {
		proxy: {
			"/api": "http://localhost:3000",
		},
	},
} satisfies UserConfigExport;
```

But I'm open to the idea of adding a few lines to the documentation (although there isn't much documentation to begin with 😅). Feel free to send a PR if you're up for it!
